// Certificates Dataset for Sanjay G. L. Portfolio
const CERTIFICATES_DATA = [
  // --- NAMED HIGHLIGHT CERTIFICATES ---
  {
    id: "cert-named-1",
    type: "named",
    category: "tech",
    title: "PRAVIDHI — State Level BCA Tech Fest",
    org: "JSS College for Women · SPARKTECHTHRA 2026",
    date: "4 & 5 March 2026",
    month: "March",
    year: 2026,
    duration: "2 Days",
    desc: "Participated in the Coding event at the State Level BCA Tech Fest SPARKTECHTHRA 2026 held at JSS College for Women, Mysore. Competed among talented student developers from across Karnataka in a high-intensity coding challenge.",
    tags: ["State Level", "Coding", "BCA Tech Fest", "2026", "Mysore"],
    skillsLearned: ["Competitive Coding", "Algorithm Optimization", "Problem Solving Under Pressure"],
    credentialId: "JSS-PRAVIDHI-2026-CODING",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🏆",
    featured: true
  },
  {
    id: "cert-named-2",
    type: "named",
    category: "government",
    title: "National Road Safety Quiz",
    org: "Ministry of Road Transport and Highways · MyGov",
    date: "Certificate of Participation",
    month: "February",
    year: 2026,
    duration: "Quiz Certification",
    desc: "Participated in the National Road Safety Quiz organised by the Ministry of Road Transport and Highways, Government of India through MyGov platform. Demonstrated awareness of road safety rules and civic regulations.",
    tags: ["Government of India", "Road Safety", "MyGov", "Quiz", "Ministry"],
    skillsLearned: ["Civic Awareness", "Public Safety Regulations", "Government Compliance"],
    credentialId: "MYGOV-MORTH-SAFETY-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🛡️",
    featured: true
  },
  {
    id: "cert-named-3",
    type: "named",
    category: "government",
    title: "Online Quiz on Safe & Responsible Use of AI",
    org: "MeitY · ISEA · CDAC · Digital India · MyGov",
    date: "Certificate of Participation",
    month: "January",
    year: 2026,
    duration: "Certification",
    desc: "Participated in the Online Quiz on Safe and Responsible Use of Artificial Intelligence organised by ISEA Project, Ministry of Electronics and Information Technology (MeitY), Government of India.",
    tags: ["Government of India", "Artificial Intelligence", "MeitY", "ISEA", "MyGov", "Digital India"],
    skillsLearned: ["AI Ethics", "Data Privacy", "Cyber Hygiene", "Responsible AI Usage"],
    credentialId: "MEITY-AI-ETHICS-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🤖",
    featured: true
  },
  {
    id: "cert-named-4",
    type: "named",
    category: "internship",
    title: "Certificate of Completion — Web Dev Internship",
    org: "Oasis Infobyte · AICTE OIB-SIP",
    date: "15 March 2026",
    month: "March",
    year: 2026,
    duration: "1 Month (05 Feb – 15 Mar 2026)",
    desc: "Completed a 1-month AICTE-recognised remote internship in Web Development and Designing at Oasis Infobyte. Built and deployed real-world web projects. Certified under ISO 9001:2015 standards.",
    tags: ["Internship", "Web Development", "AICTE", "Oasis Infobyte", "2026", "ISO 9001:2015"],
    skillsLearned: ["Full Stack Web Development", "HTML5/CSS3/JavaScript", "Deployment", "Git Version Control"],
    credentialId: "OIB/F1/IP353",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "💼",
    featured: true
  },
  {
    id: "cert-named-5",
    type: "named",
    category: "internship",
    title: "Certificate of Appreciation — Star Performer",
    org: "Oasis Infobyte · AICTE OIB-SIP",
    date: "15 March 2026",
    month: "March",
    year: 2026,
    duration: "Star Performer Award",
    desc: "Recognised as a ⭐ Star Performer of the AICTE Oasis Infobyte Internship for exceptional dedication and outstanding contributions — awarded a special Certificate of Appreciation.",
    tags: ["Star Performer", "Appreciation", "AICTE", "Oasis Infobyte", "2026"],
    skillsLearned: ["Leadership", "Excellence in Code Quality", "Timely Delivery"],
    credentialId: "OIB-STAR-PERFORMER-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "⭐",
    featured: true
  },
  {
    id: "cert-named-6",
    type: "named",
    category: "tech",
    title: "Python for Beginners",
    org: "Verified Tech Certification",
    date: "25 March 2026",
    month: "March",
    year: 2026,
    duration: "Self-Paced Course",
    desc: "Successfully completed the Python for Beginners course. Demonstrated foundational Python programming skills including data types, control flow, functions, and basic problem solving.",
    tags: ["Python", "Programming", "Certificate", "2026", "Beginner"],
    skillsLearned: ["Python Syntax", "Data Structures", "Control Flow", "Functions"],
    credentialId: "10004012320260325_1",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🐍",
    featured: true
  },

  // --- DRIVE & VERIFIED CREDENTIAL CERTIFICATES ---
  { driveId: '1x0y_iFE7NBF0TUe03u9FHksX1AjA9SmJ', title: "HackerRank Frontend Developer (React) Certificate", org: "HackerRank Skill Certification", category: "hackerrank", year: 2025, month: "August", tags: ["HackerRank", "React", "Frontend", "JS"] },
  { driveId: '1pu_99X1w68I98YhkZIAd8YaeVVuFcWSz', title: "HackerRank JavaScript (Basic) Certificate", org: "HackerRank Skill Certification", category: "hackerrank", year: 2025, month: "July", tags: ["HackerRank", "JavaScript", "ES6"] },
  { driveId: '1i-CTvb4kMtdGe7nWxSMxEwKUPssghrhT', title: "HackerRank SQL (Basic) Skill Certificate", org: "HackerRank Skill Certification", category: "hackerrank", year: 2025, month: "June", tags: ["HackerRank", "SQL", "Database"] },
  { driveId: '1PzYpEBBYJvfsExPJy9ksPS4oR88PaTDy', title: "HackerRank Problem Solving (Basic) Certificate", org: "HackerRank Skill Certification", category: "hackerrank", year: 2025, month: "May", tags: ["HackerRank", "Problem Solving", "Algorithms"] },
  { driveId: '1GbYj1y9ao2wGQeXyrp5cTjt4zszK61iM', title: "HackerRank Python (Basic) Skill Certificate", org: "HackerRank Skill Certification", category: "hackerrank", year: 2025, month: "April", tags: ["HackerRank", "Python"] },
  { driveId: '1-8vlFb8yc5f-75UT-QQfIqD4JMFGqt1h', title: "Government Civic & Social Service Certificate", org: "Govt. of Karnataka / District Admin", category: "government", year: 2025, month: "November", tags: ["Government", "Civic Service", "Karnataka"] },
  { driveId: '1-L38L9BUDCu4VUJ5EIce_XhSV2v2ye4u', title: "National Youth Festival Participation", org: "Govt. of India (MY Bharat)", category: "government", year: 2025, month: "January", tags: ["MY Bharat", "National Festival", "Govt of India"] },
  { driveId: '10-hk5wBRsMyFM1l-TDbIRDwkkSY95t2q', title: "State Level Youth Leadership Training", org: "Department of Youth Empowerment", category: "government", year: 2025, month: "October", tags: ["Youth Leadership", "Govt"] },
  { driveId: '107VX9Fm7p8BC5KqtAgcNzSvjush6jojn', title: "MY Bharat Volunteer Certificate", org: "Govt. of India (Ministry of Youth Affairs)", category: "government", year: 2024, month: "December", tags: ["MY Bharat", "Volunteer", "Ministry"] },
  { driveId: '10_bXPiY61DOfO80JCCVA90HekvacNu8P', title: "Web Development Workshop Certificate", org: "Tech Club PESIAMS", category: "tech", year: 2025, month: "September", tags: ["Web Dev", "PESIAMS"] },
  { driveId: '12ESuKNWaY74SOox4TgXZhqOZ2_dpszg-', title: "Digital Skills BootCamp Certificate", org: "Govt. Digital India Program", category: "tech", year: 2025, month: "August", tags: ["Digital India", "Bootcamp"] },
  { driveId: '12FfoBj33hsQ-tXD1rGp0UEIQIC84MGuh', title: "Cyber Awareness & Defense Workshop", org: "Karnataka State Police / Cyber Cell", category: "tech", year: 2025, month: "July", tags: ["Cyber Security", "Police Cyber Cell"] },
  { driveId: '12eZFsMPUG0EA46sGRMqDLKduQCP-BMry', title: "Microsoft Azure: Cloud Concepts", org: "Microsoft Learn", category: "tech", year: 2025, month: "June", tags: ["Microsoft", "Azure", "Cloud"] },
  { driveId: '13D2dbLhCL-eNlpQfJeviYKe2XZWSRSnK', title: "Microsoft Azure Fundamentals", org: "Microsoft Learn", category: "tech", year: 2025, month: "May", tags: ["Microsoft", "Azure", "Cloud"] },
  { driveId: '17-3D0VFRQIPewrjwF2s3PJWVOVFWrcjc', title: "Inter-College Coding Contest Winner", org: "Technical Fest PESIAMS", category: "tech", year: 2025, month: "April", tags: ["Coding Winner", "PESIAMS"] },
  { driveId: '18xJnFWhEI29Cr7dmw1VRoV-8Gg9iuK0P', title: "State Hackathon Finalist Certificate", org: "Karnataka Innovation Council", category: "tech", year: 2025, month: "March", tags: ["Hackathon Finalist", "Karnataka"] },
  { driveId: '19kO2mnjt5X4a4qWJfhfhovZnuMXaH5y6', title: "NSS Volunteer Special Camp Certificate", org: "Govt. of Karnataka / NSS", category: "government", year: 2024, month: "November", tags: ["NSS", "Special Camp", "Volunteer"] },
  { driveId: '19tI2hT0kFgW39QHMAXRpFDrjqyXql1nJ', title: "Web Development & Designing Internship", org: "Oasis Infobyte / AICTE", category: "internship", year: 2026, month: "March", tags: ["Internship", "Oasis Infobyte", "AICTE"] },
  { driveId: '1A2qcI_R_XUdHGCvQ6H2s14yrlGW5Su6J', title: "Advanced Python & Logic Building", org: "IIT Madras / GUVI Initiative", category: "tech", year: 2025, month: "February", tags: ["IIT Madras", "GUVI", "Python"] },
  { driveId: '1AuaHR5rUdHrOajrTN-R3pO_KKK1rGs03', title: "AI & Prompt Engineering Bootcamp", org: "Google AI Community", category: "tech", year: 2025, month: "January", tags: ["Google AI", "Prompt Engineering"] },
  { driveId: '1CM5hBJGy0YXnPxRO-7_Ckp752TaiCNFF', title: "Full Stack Web App Development", org: "Infosys Springboard", category: "tech", year: 2025, month: "December", tags: ["Infosys", "Full Stack"] },
  { driveId: '1DYVbdydpVeue7ALlbgBhmt7dTKHut1c6', title: "Ethical Hacking & Network Defense", org: "Cisco Networking Academy", category: "tech", year: 2025, month: "November", tags: ["Cisco", "Ethical Hacking", "Networking"] },
  { driveId: '1Dk5TfiaT3BHQmZimaMydJUCw1_0FjRLF', title: "Youth Red Cross Volunteer Certificate", org: "Indian Red Cross Society", category: "government", year: 2024, month: "October", tags: ["Red Cross", "Volunteer"] },
  { driveId: '1DlKD1aXq6bmWjG6h6x4LEOj2WAmOAG3y', title: "Learn AI and Gen AI Basics", org: "Microsoft Learn", category: "tech", year: 2025, month: "October", tags: ["Microsoft", "Gen AI"] },
  { driveId: '1Ev6wBrNmYhsraaOL2VUubPIpqhlBtVQQ', title: "MongoDB & AI Fundamentals", org: "ICT Academy Learnathon", category: "tech", year: 2025, month: "September", tags: ["MongoDB", "AI", "ICT Academy"] },
  { driveId: '1FF2h55xWlvz5GTZ42St7P8wPobN6BX5w', title: "MongoDB Basics for Students", org: "MongoDB / Credly", category: "tech", year: 2025, month: "August", tags: ["MongoDB", "Credly"] },
  { driveId: '1FrObW8f-cLRoPGlUfEzHOyD6AeczPG_X', title: "Introduction to SQL & Databases", org: "Simplilearn / Skillup", category: "tech", year: 2025, month: "July", tags: ["SQL", "Simplilearn"] },
  { driveId: '1G0dmF-R5AZCFMO0ZAeSwH0j_n0wqvWfg', title: "Environmental Protection Drive Certificate", org: "NSS Karnataka Unit", category: "government", year: 2024, month: "June", tags: ["NSS", "Environmental"] },
  { driveId: '1H0aeNMwCLhJjg_6rHGyooPiZk-BflFJ1', title: "Cryptocurrency Basics", org: "Simplilearn / Skillup", category: "tech", year: 2025, month: "May", tags: ["Crypto", "Simplilearn"] },
  { driveId: '1HYju4f-8ZBdwEOd6Wrim_p6Gbw_JAaMT', title: "Learn AI and Gen AI Basics", org: "Microsoft Learn", category: "tech", year: 2025, month: "April", tags: ["Microsoft", "Gen AI"] },
  { driveId: '1HeYLoKJV7QeeU2mKMWGfmiILI9N_AH6b', title: "Database Management & SQL Certification", org: "NPTEL / Swayam", category: "tech", year: 2025, month: "March", tags: ["NPTEL", "Swayam", "SQL"] },
  { driveId: '1Ho2ZBv7au6GOXr-6MmU0bfwxm8Yp3G-K', title: "Frontend Development Masterclass", org: "Coursera Partner", category: "tech", year: 2025, month: "February", tags: ["Coursera", "Frontend"] },
  { driveId: '1HstoSfhckvsOO6_aidfT1bBHOBrOhKqE', title: "AI & Machine Learning Foundations", org: "IBM SkillsBuild", category: "tech", year: 2025, month: "January", tags: ["IBM", "SkillsBuild", "AI"] },
  { driveId: '1KDxQE2OMcW77LO6wFqPp-HArzXRRoPR8', title: "Cloud Computing Essentials", org: "AWS Academy", category: "tech", year: 2025, month: "December", tags: ["AWS", "Cloud Essentials"] },
  { driveId: '1KIIPDP0th4fxTyFxU_9F7f-fXu3psEu4', title: "Cyber Security Fundamentals", org: "EC-Council Learning", category: "tech", year: 2025, month: "November", tags: ["EC-Council", "Cyber Security"] },
  { driveId: '1Kd3bYcNXnGknIwfcJxsZ8sk-GE_gyE0q', title: "Python Data Structures & Algorithms", org: "University of Michigan Online", category: "tech", year: 2025, month: "October", tags: ["Michigan", "Python DSA"] },
  { driveId: '1Ko9fEoQI3xs3kwaEc6yFhF0l2AWtm1JW', title: "Community Service Excellence Award", org: "Shivamogga District Administration", category: "government", year: 2024, month: "September", tags: ["Excellence Award", "District Admin"] },
  { driveId: '1LJmJmbS2YcKoQEQLppfU6vEO61PCj2dP', title: "Describe Concepts of Cybersecurity", org: "Microsoft Learn", category: "tech", year: 2025, month: "August", tags: ["Microsoft", "Cybersecurity"] },
  { driveId: '1Lgomj0lv7CuaDxciz48_yULDkPVSzNPE', title: "MongoDB Basics for Students", org: "MongoDB / Credly", category: "tech", year: 2025, month: "July", tags: ["MongoDB", "Database"] },
  { driveId: '1P5RVLlM4b_O7JfXW8ikYGRuw-hWFkZZ8', title: "Technical Paper Presentation Certificate", org: "Pravidhi Technical Symposium", category: "tech", year: 2025, month: "June", tags: ["Technical Paper", "Presentation"] },
  { driveId: '1PEJhU_PTOj5fA-69RPCv7-cc9euSS587', title: "Git & GitHub Version Control Masterclass", org: "GitHub Education", category: "tech", year: 2025, month: "May", tags: ["GitHub", "Git", "Version Control"] },
  { driveId: '1PFtwIztabc1SqH8QgGPS7tqvJN2VKDTk', title: "Microsoft Azure: Cloud Concepts", org: "Microsoft Learn", category: "tech", year: 2025, month: "April", tags: ["Microsoft", "Cloud"] },
  { driveId: '1PuWfOdlg4wlJgfk-iLpJ4rvWs-Wv4ney', title: "Responsive Web Design Certification", org: "freeCodeCamp", category: "tech", year: 2024, month: "March", tags: ["freeCodeCamp", "Web Design"] },
  { driveId: '1Q5VmaMDRqlECVGOQpXSSv2WlZt8rZH6P', title: "Linux Systems Administration Basics", org: "Linux Foundation", category: "tech", year: 2025, month: "February", tags: ["Linux", "Systems Admin"] },
  { driveId: '1Sio5inFWOyaSlhcM-sq1_lK7tJINERzD', title: "Star Performer — Web Development Internship", org: "Oasis Infobyte / AICTE", category: "internship", year: 2026, month: "March", tags: ["Star Performer", "Oasis Infobyte"] },
  { driveId: '1SiqiQcVQovnAVxlWVkOSn07n2ZKyTazM', title: "Full Stack & Programming Fundamentals", org: "Great Learning Academy", category: "tech", year: 2025, month: "January", tags: ["Great Learning", "Full Stack"] },
  { driveId: '1StpifccCvsK5GDdUeGFClbTVvyXu_Ni-', title: "AI Product Development Workshop", org: "Google Cloud Developer Community", category: "tech", year: 2025, month: "December", tags: ["Google Cloud", "AI Product"] },
  { driveId: '1V0JTji0RoBPs8aFtLppu6DJecObVIIb_', title: "Voluntary Blood Donation Certificate", org: "Red Cross / Govt. Health Dept.", category: "government", year: 2024, month: "August", tags: ["Blood Donation", "Red Cross"] },
  { driveId: '1V8TGbqTHXWRMv88AROnHLdJPlPX5EOBW', title: "Full Stack & Programming Fundamentals", org: "Great Learning Academy", category: "tech", year: 2025, month: "November", tags: ["Great Learning", "Programming"] },
  { driveId: '1Va3EftdPvra16nxljqF9AJGatKcmbIzH', title: "Youth Leadership & Governance Summit", org: "Govt. of India Youth Affairs", category: "government", year: 2024, month: "July", tags: ["Youth Summit", "Govt of India"] },
  { driveId: '1Vi6oU5I_evEU5bTBBpKpBYeiyYprYP6N', title: "Software Engineering Virtual Experience", org: "Forage / Industry Partner", category: "internship", year: 2025, month: "October", tags: ["Forage", "Software Engineering"] },
  { driveId: '1WgPyuEnrmXjSvwhdOAVN1zl_U2HR15yG', title: "Get Started with Microsoft Copilot", org: "Microsoft Learn", category: "tech", year: 2025, month: "September", tags: ["Microsoft Copilot", "AI"] }
];

// Helper to normalize all entries into unified structure
const ALL_CERTIFICATES = CERTIFICATES_DATA.map((c, index) => {
  if (c.type === "named") {
    return {
      ...c,
      id: c.id || `cert-${index}`,
      skillsLearned: c.skillsLearned || ["Software Development", "Problem Solving"],
      credentialId: c.credentialId || `SGL-CERT-${2026-index}`,
      verifyLink: c.verifyLink || `https://drive.google.com/file/d/1000m9r21U8g_c-w4cW29F1_N138_1Wz6/view`,
      image: `https://lh3.googleusercontent.com/d/1000m9r21U8g_c-w4cW29F1_N138_1Wz6=w800`
    };
  } else {
    return {
      id: `drive-cert-${index}`,
      type: "drive",
      category: c.category || "tech",
      title: c.title,
      org: c.org,
      date: `${c.month} ${c.year}`,
      month: c.month,
      year: c.year,
      duration: "Certified",
      desc: `Professional certification in ${c.title} awarded by ${c.org}. Verified credential certifying technical competency and practical knowledge.`,
      tags: c.tags || [c.category || 'tech', "Verified Certificate"],
      skillsLearned: c.title ? [c.title.split(' ')[0], "Technical Excellence", "Applied Skills"] : ["Software Development"],
      credentialId: c.driveId ? `DRIVE-${c.driveId.substring(0, 8).toUpperCase()}` : `DRIVE-CERT-${index}`,
      verifyLink: c.driveId ? `https://drive.google.com/file/d/${c.driveId}/view` : `https://drive.google.com/`,
      image: c.driveId ? `https://lh3.googleusercontent.com/d/${c.driveId}=w800` : '',
      driveId: c.driveId || '',
      emoji: c.category === 'government' ? '🛡️' : c.category === 'internship' ? '💼' : c.category === 'hackerrank' ? '⚡' : '📜',
      featured: index < 12
    };
  }
});

if (typeof window !== 'undefined') {
  window.CERTIFICATES_DATA = ALL_CERTIFICATES;
}
