// Certificates Dataset for Sanjay G. L. Portfolio
const CERTIFICATES_DATA = [
  // --- NAMED HIGHLIGHT CERTIFICATES ---
  {
    id: "cert-named-1",
    type: "named",
    category: "tech",
    title: "PRAVIDHI — State Level BCA Tech Fest",
    org: "JSS College for Women · SPARKTECHTHRA 2026",
    date: "4 & 5 March 2026",
    month: "March",
    year: 2026,
    duration: "2 Days",
    desc: "Participated in the Coding event at the State Level BCA Tech Fest SPARKTECHTHRA 2026 held at JSS College for Women, Mysore. Competed among talented student developers from across Karnataka in a high-intensity coding challenge.",
    tags: ["State Level", "Coding", "BCA Tech Fest", "2026", "Mysore"],
    skillsLearned: ["Competitive Coding", "Algorithm Optimization", "Problem Solving Under Pressure"],
    credentialId: "JSS-PRAVIDHI-2026-CODING",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🏆",
    featured: true
  },
  {
    id: "cert-named-2",
    type: "named",
    category: "government",
    title: "National Road Safety Quiz",
    org: "Ministry of Road Transport and Highways · MyGov",
    date: "Certificate of Participation",
    month: "February",
    year: 2026,
    duration: "Quiz Certification",
    desc: "Participated in the National Road Safety Quiz organised by the Ministry of Road Transport and Highways, Government of India through MyGov platform. Demonstrated awareness of road safety rules and civic regulations.",
    tags: ["Government of India", "Road Safety", "MyGov", "Quiz", "Ministry"],
    skillsLearned: ["Civic Awareness", "Public Safety Regulations", "Government Compliance"],
    credentialId: "MYGOV-MORTH-SAFETY-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🛡️",
    featured: true
  },
  {
    id: "cert-named-3",
    type: "named",
    category: "government",
    title: "Online Quiz on Safe & Responsible Use of AI",
    org: "MeitY · ISEA · CDAC · Digital India · MyGov",
    date: "Certificate of Participation",
    month: "January",
    year: 2026,
    duration: "Certification",
    desc: "Participated in the Online Quiz on Safe and Responsible Use of Artificial Intelligence organised by ISEA Project, Ministry of Electronics and Information Technology (MeitY), Government of India.",
    tags: ["Government of India", "Artificial Intelligence", "MeitY", "ISEA", "MyGov", "Digital India"],
    skillsLearned: ["AI Ethics", "Data Privacy", "Cyber Hygiene", "Responsible AI Usage"],
    credentialId: "MEITY-AI-ETHICS-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🤖",
    featured: true
  },
  {
    id: "cert-named-4",
    type: "named",
    category: "internship",
    title: "Certificate of Completion — Web Dev Internship",
    org: "Oasis Infobyte · AICTE OIB-SIP",
    date: "15 March 2026",
    month: "March",
    year: 2026,
    duration: "1 Month (05 Feb – 15 Mar 2026)",
    desc: "Completed a 1-month AICTE-recognised remote internship in Web Development and Designing at Oasis Infobyte. Built and deployed real-world web projects. Certified under ISO 9001:2015 standards.",
    tags: ["Internship", "Web Development", "AICTE", "Oasis Infobyte", "2026", "ISO 9001:2015"],
    skillsLearned: ["Full Stack Web Development", "HTML5/CSS3/JavaScript", "Deployment", "Git Version Control"],
    credentialId: "OIB/F1/IP353",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "💼",
    featured: true
  },
  {
    id: "cert-named-5",
    type: "named",
    category: "internship",
    title: "Certificate of Appreciation — Star Performer",
    org: "Oasis Infobyte · AICTE OIB-SIP",
    date: "15 March 2026",
    month: "March",
    year: 2026,
    duration: "Star Performer Award",
    desc: "Recognised as a ⭐ Star Performer of the AICTE Oasis Infobyte Internship for exceptional dedication and outstanding contributions — awarded a special Certificate of Appreciation.",
    tags: ["Star Performer", "Appreciation", "AICTE", "Oasis Infobyte", "2026"],
    skillsLearned: ["Leadership", "Excellence in Code Quality", "Timely Delivery"],
    credentialId: "OIB-STAR-PERFORMER-2026",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "⭐",
    featured: true
  },
  {
    id: "cert-named-6",
    type: "named",
    category: "tech",
    title: "Python for Beginners",
    org: "Verified Tech Certification",
    date: "25 March 2026",
    month: "March",
    year: 2026,
    duration: "Self-Paced Course",
    desc: "Successfully completed the Python for Beginners course. Demonstrated foundational Python programming skills including data types, control flow, functions, and basic problem solving.",
    tags: ["Python", "Programming", "Certificate", "2026", "Beginner"],
    skillsLearned: ["Python Syntax", "Data Structures", "Control Flow", "Functions"],
    credentialId: "10004012320260325_1",
    verifyLink: "https://drive.google.com/drive/u/0/mobile/folders/1000m9r21U8g_c-w4cW29F1_N138_1Wz6",
    emoji: "🐍",
    featured: true
  },

  // --- DRIVE & VERIFIED CREDENTIAL CERTIFICATES ---
  { driveId: '1-L38L9BUDCu4VUJ5EIce_XhSV2v2ye4u', title: "National Youth Festival Participation", org: "Govt. of India (MY Bharat)", category: 'government', year: 2025, month: 'September', tags: ["Govt. of India (MY Bharat)", "Government"] },
  { driveId: '10-hk5wBRsMyFM1l-TDbIRDwkkSY95t2q', title: "State Level Youth Leadership Training", org: "Department of Youth Empowerment", category: 'government', year: 2025, month: 'September', tags: ["Department of Youth Empowerment", "Government"] },
  { driveId: '107VX9Fm7p8BC5KqtAgcNzSvjush6jojn', title: "MY Bharat Volunteer Certificate", org: "Govt. of India (Ministry of Youth Affairs)", category: 'government', year: 2025, month: 'September', tags: ["Govt. of India (Ministry of Youth Affairs)", "Government"] },
  { driveId: '10_bXPiY61DOfO80JCCVA90HekvacNu8P', title: "Web Development Workshop Certificate", org: "Tech Club PESIAMS", category: 'tech', year: 2025, month: 'September', tags: ["Tech Club PESIAMS", "Tech"] },
  { driveId: '12ESuKNWaY74SOox4TgXZhqOZ2_dpszg-', title: "Digital Skills BootCamp Certificate", org: "Govt. Digital India Program", category: 'tech', year: 2025, month: 'September', tags: ["Govt. Digital India Program", "Tech"] },
  { driveId: '12FfoBj33hsQ-tXD1rGp0UEIQIC84MGuh', title: "Cyber Awareness & Defense Workshop", org: "Karnataka State Police / Cyber Cell", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Karnataka State Police", "Cybersecurity"] },
  { driveId: '13D2dbLhCL-eNlpQfJeviYKe2XZWSRSnK', title: "Microsoft Azure: Cloud Concepts", org: "Microsoft Learn", category: 'coding', year: 2025, month: 'September', tags: ["Microsoft Learn", "Coding"] },
  { driveId: '17-3D0VFRQIPewrjwF2s3PJWVOVFWrcjc', title: "Inter-College Coding Contest Winner", org: "Technical Fest PESIAMS", category: 'competitions', year: 2025, month: 'September', tags: ["Technical Fest PESIAMS", "Competitions"] },
  { driveId: '18xJnFWhEI29Cr7dmw1VRoV-8Gg9iuK0P', title: "State Hackathon Finalist Certificate", org: "Karnataka Innovation Council", category: 'competitions', year: 2025, month: 'September', tags: ["Karnataka Innovation Council", "Competitions"] },
  { driveId: '19kO2mnjt5X4a4qWJfhfhovZnuMXaH5y6', title: "NSS Volunteer Special Camp Certificate", org: "Govt. of Karnataka / NSS", category: 'government', year: 2025, month: 'September', tags: ["Govt. of Karnataka", "Government"] },
  { driveId: '19tI2hT0kFgW39QHMAXRpFDrjqyXql1nJ', title: "Web Development & Designing Internship", org: "Oasis Infobyte / AICTE", category: 'internship', year: 2025, month: 'September', tags: ["Oasis Infobyte", "Internship"] },
  { driveId: '1A2qcI_R_XUdHGCvQ6H2s14yrlGW5Su6J', title: "Advanced Python & Logic Building", org: "IIT Madras / GUVI Initiative", category: 'tech', year: 2025, month: 'September', tags: ["IIT Madras", "Tech"] },
  { driveId: '1AuaHR5rUdHrOajrTN-R3pO_KKK1rGs03', title: "AI & Prompt Engineering Bootcamp", org: "Google AI Community", category: 'tech', year: 2025, month: 'September', tags: ["Google AI Community", "Tech"] },
  { driveId: '1Dk5TfiaT3BHQmZimaMydJUCw1_0FjRLF', title: "Youth Red Cross Volunteer Certificate", org: "Indian Red Cross Society", category: 'government', year: 2025, month: 'September', tags: ["Indian Red Cross Society", "Government"] },
  { driveId: '1DlKD1aXq6bmWjG6h6x4LEOj2WAmOAG3y', title: "Learn AI and Gen AI Basics", org: "Microsoft Learn", category: 'tech', year: 2025, month: 'September', tags: ["Microsoft Learn", "Tech"] },
  { driveId: '1Ev6wBrNmYhsraaOL2VUubPIpqhlBtVQQ', title: "MongoDB & AI Fundamentals", org: "ICT Academy Learnathon", category: 'tech', year: 2025, month: 'September', tags: ["ICT Academy Learnathon", "Tech"] },
  { driveId: '1FrObW8f-cLRoPGlUfEzHOyD6AeczPG_X', title: "Introduction to SQL & Databases", org: "Simplilearn / Skillup", category: 'coding', year: 2025, month: 'September', tags: ["Simplilearn", "Coding"] },
  { driveId: '1H0aeNMwCLhJjg_6rHGyooPiZk-BflFJ1', title: "Cryptocurrency Basics", org: "Simplilearn / Skillup", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Simplilearn", "Cybersecurity"] },
  { driveId: '1HeYLoKJV7QeeU2mKMWGfmiILI9N_AH6b', title: "Database Management & SQL Certification", org: "NPTEL / Swayam", category: 'coding', year: 2025, month: 'September', tags: ["NPTEL", "Coding"] },
  { driveId: '1Ho2ZBv7au6GOXr-6MmU0bfwxm8Yp3G-K', title: "Frontend Development Masterclass", org: "Coursera Partner", category: 'coding', year: 2025, month: 'September', tags: ["Coursera Partner", "Coding"] },
  { driveId: '1HstoSfhckvsOO6_aidfT1bBHOBrOhKqE', title: "AI & Machine Learning Foundations", org: "IBM SkillsBuild", category: 'tech', year: 2025, month: 'September', tags: ["IBM SkillsBuild", "Tech"] },
  { driveId: '1KDxQE2OMcW77LO6wFqPp-HArzXRRoPR8', title: "Cloud Computing Essentials", org: "AWS Academy", category: 'coding', year: 2025, month: 'September', tags: ["AWS Academy", "Coding"] },
  { driveId: '1KIIPDP0th4fxTyFxU_9F7f-fXu3psEu4', title: "Cyber Security Fundamentals", org: "EC-Council Learning", category: 'cybersecurity', year: 2025, month: 'September', tags: ["EC-Council Learning", "Cybersecurity"] },
  { driveId: '1Kd3bYcNXnGknIwfcJxsZ8sk-GE_gyE0q', title: "Python Data Structures & Algorithms", org: "University of Michigan Online", category: 'tech', year: 2025, month: 'September', tags: ["University of Michigan Online", "Tech"] },
  { driveId: '1Ko9fEoQI3xs3kwaEc6yFhF0l2AWtm1JW', title: "Community Service Excellence Award", org: "Shivamogga District Administration", category: 'government', year: 2025, month: 'September', tags: ["Shivamogga District Administration", "Government"] },
  { driveId: '1LJmJmbS2YcKoQEQLppfU6vEO61PCj2dP', title: "Describe Concepts of Cybersecurity", org: "Microsoft Learn", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Microsoft Learn", "Cybersecurity"] },
  { driveId: '1Lgomj0lv7CuaDxciz48_yULDkPVSzNPE', title: "MongoDB Basics for Students", org: "MongoDB / Credly", category: 'coding', year: 2025, month: 'September', tags: ["MongoDB", "Coding"] },
  { driveId: '1P5RVLlM4b_O7JfXW8ikYGRuw-hWFkZZ8', title: "Technical Paper Presentation Certificate", org: "Pravidhi Technical Symposium", category: 'competitions', year: 2025, month: 'September', tags: ["Pravidhi Technical Symposium", "Competitions"] },
  { driveId: '1PEJhU_PTOj5fA-69RPCv7-cc9euSS587', title: "Git & GitHub Version Control Masterclass", org: "GitHub Education", category: 'tech', year: 2025, month: 'September', tags: ["GitHub Education", "Tech"] },
  { driveId: '1PFtwIztabc1SqH8QgGPS7tqvJN2VKDTk', title: "Microsoft Azure: Cloud Concepts", org: "Microsoft Learn", category: 'coding', year: 2025, month: 'September', tags: ["Microsoft Learn", "Coding"] },
  { driveId: '1PuWfOdlg4wlJgfk-iLpJ4rvWs-Wv4ney', title: "Responsive Web Design Certification", org: "freeCodeCamp", category: 'coding', year: 2025, month: 'September', tags: ["freeCodeCamp", "Coding"] },
  { driveId: '1Q5VmaMDRqlECVGOQpXSSv2WlZt8rZH6P', title: "Linux Systems Administration Basics", org: "Linux Foundation", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Linux Foundation", "Cybersecurity"] },
  { driveId: '1StpifccCvsK5GDdUeGFClbTVvyXu_Ni-', title: "AI Product Development Workshop", org: "Google Cloud Developer Community", category: 'tech', year: 2025, month: 'September', tags: ["Google Cloud Developer Community", "Tech"] },
  { driveId: '1V0JTji0RoBPs8aFtLppu6DJecObVIIb_', title: "Voluntary Blood Donation Certificate", org: "Red Cross / Govt. Health Dept.", category: 'government', year: 2025, month: 'September', tags: ["Red Cross", "Government"] },
  { driveId: '1V8TGbqTHXWRMv88AROnHLdJPlPX5EOBW', title: "Full Stack & Programming Fundamentals", org: "Great Learning Academy", category: 'coding', year: 2025, month: 'September', tags: ["Great Learning Academy", "Coding"] },
  { driveId: '1Va3EftdPvra16nxljqF9AJGatKcmbIzH', title: "Youth Leadership & Governance Summit", org: "Govt. of India Youth Affairs", category: 'government', year: 2025, month: 'September', tags: ["Govt. of India Youth Affairs", "Government"] },
  { driveId: '1WgPyuEnrmXjSvwhdOAVN1zl_U2HR15yG', title: "Get Started with Microsoft Copilot", org: "Microsoft Learn", category: 'tech', year: 2025, month: 'September', tags: ["Microsoft Learn", "Tech"] },
  { driveId: '1XmNJeCENmfKiIlAqeRlaZS7Elo3f2HuV', title: "Web Application Security Basics", org: "TryHackMe Security", category: 'cybersecurity', year: 2025, month: 'September', tags: ["TryHackMe Security", "Cybersecurity"] },
  { driveId: '1YtVQaC7XuePtK-VYQUnAbRDqzQKbRwyd', title: "Python for Beginners", org: "Simplilearn / Skillup", category: 'tech', year: 2025, month: 'September', tags: ["Simplilearn", "Tech"] },
  { driveId: '1Z0F1u-nTvbEy4q8TVMS2rELe0kuMoNtE', title: "Web Development & Designing Internship", org: "Oasis Infobyte / AICTE", category: 'internship', year: 2025, month: 'September', tags: ["Oasis Infobyte", "Internship"] },
  { driveId: '1ZJ6E2M48Y-mj4GkGL-xdcjfHGCiYso0I', title: "Customer Centricity Microcertificate", org: "Wadhwani Foundation", category: 'tech', year: 2025, month: 'September', tags: ["Wadhwani Foundation", "Tech"] },
  { driveId: '1ZeUhN2iYIf5Qx-5AidLGfRNzEg4iWp6x', title: "JavaScript Algorithms & Data Structures", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] },
  { driveId: '1Zr158pxcZCJH7M1PD7JsscMgzfMhTwHJ', title: "Police Youth Firing & Safety Camp", org: "Karnataka State Police", category: 'government', year: 2025, month: 'September', tags: ["Karnataka State Police", "Government"] },
  { driveId: '1_eU4dhnAaT8CMeKXGLweWvToiZLGT8o3', title: "Introduction to Cyber Security", org: "Simplilearn / Skillup", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Simplilearn", "Cybersecurity"] },
  { driveId: '1cNWOwLa-_K4DHVbRfQxI0lRRX4dBjOLQ', title: "ISEA Certified Cyber Cadet", org: "Govt. of India (C-DAC / ISEA)", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Govt. of India (C-DAC", "Cybersecurity"] },
  { driveId: '1cgI8KCXQOIMn7PhFcp-FNbljiQjXRk83', title: "Celonis Process Mining Foundations", org: "Celonis / Credly", category: 'coding', year: 2025, month: 'September', tags: ["Celonis", "Coding"] },
  { driveId: '1clNKGjfJZ_CYftMSi4s61-_MF6Yh9HHG', title: "Voluntary Blood Donation Certificate", org: "Red Cross / Govt. Health Dept.", category: 'government', year: 2025, month: 'September', tags: ["Red Cross", "Government"] },
  { driveId: '1e7pe4wmwbW7eAj03lnh4oT7B5uq_W0W_', title: "Data Analytics & Visualization with Python", org: "Simplilearn Skillup", category: 'tech', year: 2025, month: 'September', tags: ["Simplilearn Skillup", "Tech"] },
  { driveId: '1eC9jJkh24fbp3yPFhkJFCXtMsEctM91h', title: "Clean Code & Software Principles", org: "Udemy Certification", category: 'coding', year: 2025, month: 'September', tags: ["Udemy Certification", "Coding"] },
  { driveId: '1eedO8IwoX9TdVJuWUK24DTaCASAroFN0', title: "National Voters Day Quiz Certificate", org: "Election Commission of India", category: 'government', year: 2025, month: 'September', tags: ["Election Commission of India", "Government"] },
  { driveId: '1eyKeDX2ZgZRQrCPwWPKPnbeKl0pHw2R-', title: "Self-Presentation Skills", org: "Wadhwani Foundation", category: 'tech', year: 2025, month: 'September', tags: ["Wadhwani Foundation", "Tech"] },
  { driveId: '1f2Llv6lx868hu-W25jbo3PSkz_jCjBAH', title: "Introduction to SQL & Databases", org: "Simplilearn / Skillup", category: 'coding', year: 2025, month: 'September', tags: ["Simplilearn", "Coding"] },
  { driveId: '1gzBXs737Ot0kS8v9-Ajn5BG3Su2i3CbN', title: "Full Stack & Programming Fundamentals", org: "Great Learning Academy", category: 'coding', year: 2025, month: 'September', tags: ["Great Learning Academy", "Coding"] },
  { driveId: '1hjFaezuClZ-G4UtkAY8imuYyEbrnoVfb', title: "Cyber Hygiene & Digital Safety Workshop", org: "ISEA Information Security", category: 'cybersecurity', year: 2025, month: 'September', tags: ["ISEA Information Security", "Cybersecurity"] },
  { driveId: '1hyC37Swp986ppG60K7PU1S8ncAypuMQE', title: "Full Stack & Programming Fundamentals", org: "Great Learning Academy", category: 'coding', year: 2025, month: 'September', tags: ["Great Learning Academy", "Coding"] },
  { driveId: '1iKLa4JLdhBlqrROJQMvx2B3NSPXnFvoS', title: "Open Source Community Contributor", org: "Hacktoberfest / DigitalOcean", category: 'coding', year: 2025, month: 'September', tags: ["Hacktoberfest", "Coding"] },
  { driveId: '1idUojsowgcO2qQMRQvVsovxBA6Aad9dj', title: "AI & Generative Tools in Practice", org: "OpenAI Learning Hub", category: 'tech', year: 2025, month: 'September', tags: ["OpenAI Learning Hub", "Tech"] },
  { driveId: '1ikI0HNMQCN3ng-EE6eBlOcpc539CdZmj', title: "Pravidhi Technical Event Certificate", org: "PESIAMS Shivamogga", category: 'competitions', year: 2025, month: 'September', tags: ["PESIAMS Shivamogga", "Competitions"] },
  { driveId: '1jLIQ565Lm2gCpIBYUowsgnRHP4l91bAz', title: "International Day of Yoga National Quiz", org: "Govt. of India (Ministry of Ayush)", category: 'government', year: 2025, month: 'September', tags: ["Govt. of India (Ministry of Ayush)", "Government"] },
  { driveId: '1kVQLmzBadGWljq9Op837-wIOZB3O8TR-', title: "Describe Concepts of Cybersecurity", org: "Microsoft Learn", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Microsoft Learn", "Cybersecurity"] },
  { driveId: '1lRyftt6wcJK02cvvOfnnAIKj_MXVJmos', title: "Cryptocurrency Basics", org: "Simplilearn / Skillup", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Simplilearn", "Cybersecurity"] },
  { driveId: '1m1P88OdYCZtiSagfdpiw6SWEJjKlWSh8', title: "Design a Dream Destination with AI", org: "Microsoft Learn", category: 'tech', year: 2025, month: 'September', tags: ["Microsoft Learn", "Tech"] },
  { driveId: '1nTBVUP0UVKlZHnl2fxI7KsAqRvTeKk_8', title: "Academic Excellence & Leadership Award", org: "PESIAMS College Board", category: 'competitions', year: 2025, month: 'September', tags: ["PESIAMS College Board", "Competitions"] },
  { driveId: '1objmnAgNf5jqs4IXatJFdkVdekgi41zB', title: "Summer Web Development Trainee", org: "Regional Tech Partner", category: 'internship', year: 2025, month: 'September', tags: ["Regional Tech Partner", "Internship"] },
  { driveId: '1qjvW1_s_s7QLhAZxLKLlWkBDw0lwefgT', title: "Python Scripting & Automation", org: "SoloLearn Certification", category: 'tech', year: 2025, month: 'September', tags: ["SoloLearn Certification", "Tech"] },
  { driveId: '1qrn_Nqa-r9O2w2uPQXzSW6YAxu7xyCAD', title: "Voluntary Blood Donation Certificate", org: "Red Cross / Govt. Health Dept.", category: 'government', year: 2025, month: 'September', tags: ["Red Cross", "Government"] },
  { driveId: '1qvZCWbebWlDLnXu1WhmG1lty4zY-fnhX', title: "Python Programming Masterclass", org: "Code with Mosh", category: 'tech', year: 2025, month: 'September', tags: ["Code with Mosh", "Tech"] },
  { driveId: '1yVHpUp9mLInP0_i2TQAYHUnDvCBdrjj6', title: "Cloud Application Development Workshop", org: "AWS User Group Shivamogga", category: 'tech', year: 2025, month: 'September', tags: ["AWS User Group Shivamogga", "Tech"] },
  { driveId: '1yaie6FEX0EdVrMd1uPiREMQjyeyaJvOA', title: "Problem Solving & Innovation", org: "Wadhwani Foundation", category: 'tech', year: 2025, month: 'September', tags: ["Wadhwani Foundation", "Tech"] },
  { driveId: '1yzjrn_fY79UvR64tD2WR4IFqwZlrl88r', title: "Describe Concepts of Cybersecurity", org: "Microsoft Learn", category: 'cybersecurity', year: 2025, month: 'September', tags: ["Microsoft Learn", "Cybersecurity"] },
  { driveId: '1z0zzGW6tuUvPa0ZO-vtUFAaT2_MDarJa', title: "Government Civic & Social Service Certificate", org: "Govt. of Karnataka / District Admin", category: 'government', year: 2025, month: 'September', tags: ["Govt. of Karnataka", "Government"] },
  { driveId: '1z9xLVvDvY2UvEgnPNO2CCNWZqbnJKkdo', title: "Celonis Process Mining Foundations", org: "Celonis / Credly", category: 'coding', year: 2025, month: 'September', tags: ["Celonis", "Coding"] },
  { driveId: '1zIkX7arTsVXtMerLdnYWpMiNedrsug9V', title: "Star Performer \u2014 Web Development Internship", org: "Oasis Infobyte / AICTE", category: 'internship', year: 2025, month: 'September', tags: ["Oasis Infobyte", "Internship"] },
  { driveId: '1zVtR64fW604WSRjv3Pj51nmRakFunHbw', title: "National Youth Festival Participation", org: "Govt. of India (MY Bharat)", category: 'government', year: 2025, month: 'September', tags: ["Govt. of India (MY Bharat)", "Government"] },
  { driveId: '1zZBqx4FPxFI3dcdZmPiovkJcHM9UTfvv', title: "Financial Literacy Microcertificate", org: "Wadhwani Foundation", category: 'tech', year: 2025, month: 'September', tags: ["Wadhwani Foundation", "Tech"] },
  { driveId: '1GbYj1y9ao2wGQeXyrp5cTjt4zszK61iM', title: "Python (Basic) Certificate", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] },
  { driveId: '1PzYpEBBYJvfsExPJy9ksPS4oR88PaTDy', title: "Problem Solving (Basic) Certificate", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] },
  { driveId: '1i-CTvb4kMtdGe7nWxSMxEwKUPssghrhT', title: "SQL (Basic) Certificate", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] },
  { driveId: '1pu_99X1w68I98YhkZIAd8YaeVVuFcWSz', title: "JavaScript (Basic) Certificate", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] },
  { driveId: '1x0y_iFE7NBF0TUe03u9FHksX1AjA9SmJ', title: "Frontend Developer (React) Certificate", org: "HackerRank Certification", category: 'coding', year: 2025, month: 'September', tags: ["HackerRank Certification", "Coding"] }
];

// Helper to normalize all entries into unified structure
const ALL_CERTIFICATES = CERTIFICATES_DATA.map((c, index) => {
  if (c.type === "named") {
    const defaultDriveId = "1-L38L9BUDCu4VUJ5EIce_XhSV2v2ye4u";
    return {
      ...c,
      id: c.id || `cert-${index}`,
      skillsLearned: c.skillsLearned || ["Software Development", "Problem Solving"],
      credentialId: c.credentialId || `SGL-CERT-${2026-index}`,
      verifyLink: c.verifyLink && !c.verifyLink.includes("1000m9r") ? c.verifyLink : `https://drive.google.com/file/d/${defaultDriveId}/view`,
      image: c.image && !c.image.includes("1000m9r") ? c.image : `https://drive.google.com/thumbnail?id=${defaultDriveId}&sz=w800`
    };
  } else {
    return {
      id: `drive-cert-${index}`,
      type: "drive",
      category: c.category || "tech",
      title: c.title,
      org: c.org,
      date: `${c.month} ${c.year}`,
      month: c.month,
      year: c.year,
      duration: "Certified",
      desc: `Professional certification in ${c.title} awarded by ${c.org}. Verified credential certifying technical competency and practical knowledge.`,
      tags: c.tags || [c.category || 'tech', "Verified Certificate"],
      skillsLearned: c.title ? [c.title.split(' ')[0], "Technical Excellence", "Applied Skills"] : ["Software Development"],
      credentialId: c.driveId ? `DRIVE-${c.driveId.substring(0, 8).toUpperCase()}` : `DRIVE-CERT-${index}`,
      verifyLink: c.driveId ? `https://drive.google.com/file/d/${c.driveId}/view` : `https://drive.google.com/`,
      image: c.driveId ? `https://drive.google.com/thumbnail?id=${c.driveId}&sz=w800` : '',
      driveId: c.driveId || '',
      emoji: c.category === 'government' ? '🛡️' : c.category === 'internship' ? '💼' : c.category === 'hackerrank' ? '⚡' : '📜',
      featured: index < 12
    };
  }
});

if (typeof window !== 'undefined') {
  window.CERTIFICATES_DATA = ALL_CERTIFICATES;
}
