// Projects Dataset for Sanjay G. L. Portfolio
const PROJECTS_DATA = [
  {
    id: 1,
    title: "AI Agent using Google API",
    year: 2025,
    category: "AI",
    tagline: "Autonomous assistant powered by Google AI APIs for intelligent conversations & task automation.",
    desc: "An AI-powered assistant integrated with Google AI APIs for intelligent conversations, reasoning, and context-aware task automation.",
    tech: ["Python", "HTML5", "CSS3", "JavaScript", "Google AI API", "Google Cloud Run"],
    live: "https://untitled-138389699449.asia-southeast1.run.app/",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-robot"
  },
  {
    id: 2,
    title: "BMI Calculator",
    year: 2025,
    category: "Utility",
    tagline: "Instant health index calculator for height and weight measurements.",
    desc: "Responsive BMI calculator providing immediate body mass index feedback, healthy range charts, and personalized health indicators.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-calculator"
  },
  {
    id: 3,
    title: "Digital Board Duel",
    year: 2025,
    category: "Game",
    tagline: "Interactive two-player digital board game with real-time turns & smooth UI.",
    desc: "Interactive Tic-Tac-Toe duel featuring modern glassmorphic design, score history, sound effects, and smooth turn animations.",
    tech: ["TypeScript", "React", "CSS3", "Tailwind CSS"],
    live: "https://digital-board-duel.lovable.app/",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-gamepad"
  },
  {
    id: 4,
    title: "RupeeTrack (Expense Tracker)",
    year: 2025,
    category: "Finance",
    tagline: "Comprehensive personal finance & expense tracking web application.",
    desc: "Modern expense tracker enabling users to log transactions, classify income/expenses, monitor monthly budgets, and analyze spending habits.",
    tech: ["HTML5", "CSS3", "JavaScript", "LocalStorage"],
    live: "https://rupeetrack-app.netlify.app/",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-wallet"
  },
  {
    id: 5,
    title: "Grab Notes",
    year: 2025,
    category: "Productivity",
    tagline: "Smart note-taking application for quick capture and seamless note management.",
    desc: "Clean note-taking suite with quick tag filtering, search indexing, auto-save drafts, and rich markdown text rendering.",
    tech: ["TypeScript", "React", "Tailwind CSS"],
    live: "https://grab-notes.base44.app",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-note-sticky"
  },
  {
    id: 6,
    title: "Handcrafted with Love – Pure Weaves",
    year: 2025,
    category: "E-Commerce",
    tagline: "Boutique showcase for artisanal handcrafted sarees & traditional weaves.",
    desc: "Elegant storefront for traditional sarees featuring high-definition photo galleries, product filtering, and order inquiry workflows.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-store"
  },
  {
    id: 7,
    title: "Hyper Rent Local",
    year: 2025,
    category: "Real Estate",
    tagline: "Local rental property discovery and tenant management platform.",
    desc: "Geolocated rental listing dashboard connecting property owners with prospective tenants for streamlined bookings.",
    tech: ["TypeScript", "React", "Tailwind CSS"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "In Progress",
    featured: false,
    icon: "fa-house-user"
  },
  {
    id: 8,
    title: "Kai Assistant",
    year: 2025,
    category: "AI",
    tagline: "In-browser conversational AI assistant built for instant answers.",
    desc: "Lightweight browser-based virtual assistant capable of quick question answering, task prompts, and contextual text generation.",
    tech: ["HTML5", "CSS3", "JavaScript", "AI API"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-brain"
  },
  {
    id: 9,
    title: "PES Placement",
    year: 2025,
    category: "Education",
    tagline: "Student placement update portal for campus recruitment drives.",
    desc: "Placement updates portal delivering real-time notifications about campus placement schedules, drive eligibility, and interview tips.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-graduation-cap"
  },
  {
    id: 10,
    title: "Placement PES IAMS",
    year: 2026,
    category: "Education",
    tagline: "Comprehensive campus placement management system for PES IAMS students.",
    desc: "Full-scale institutional portal for tracking student placement status, resume verification, company drives, and recruiter dashboards.",
    tech: ["HTML5", "CSS3", "JavaScript", "Python"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "In Progress",
    featured: true,
    icon: "fa-school"
  },
  {
    id: 11,
    title: "Pizza Shop Website",
    year: 2025,
    category: "Landing Page",
    tagline: "Mouth-watering pizza restaurant landing page with online order preview.",
    desc: "Dynamic landing page for an artisanal pizzeria featuring interactive menu selection, customization preview, and delivery zone checker.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-pizza-slice"
  },
  {
    id: 12,
    title: "Property Manager Dashboard",
    year: 2025,
    category: "Dashboard",
    tagline: "Admin dashboard for real-estate property listings & tenant management.",
    desc: "Administrative dashboard with analytics charts, tenant rent status, maintenance requests, and property unit occupancy trackers.",
    tech: ["TypeScript", "React", "Tailwind CSS"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-chart-line"
  },
  {
    id: 13,
    title: "Pure Weaves E-Commerce",
    year: 2025,
    category: "E-Commerce",
    tagline: "Full storefront for handcrafted sarees with Google Sheets backend integration.",
    desc: "Full-featured e-commerce platform using Google Apps Script as a serverless database backend to fetch live inventory and process inquiries.",
    tech: ["HTML5", "CSS3", "JavaScript", "Google Apps Script"],
    live: "https://pureweaves.vercel.app/",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-bag-shopping"
  },
  {
    id: 14,
    title: "Registration Form",
    year: 2025,
    category: "Form",
    tagline: "Clean modern user registration form with CSS validation UI.",
    desc: "Interactive registration form featuring real-time input validation, password strength meter, and polished micro-animations.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-id-card"
  },
  {
    id: 15,
    title: "Sanjay GL Portfolio",
    year: 2025,
    category: "Portfolio",
    tagline: "Personal portfolio showcasing projects, credentials, and technical skills.",
    desc: "Responsive developer website showcasing projects, skills, education timeline, and contact pathways.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "https://sanjaygl2006.vercel.app/",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-globe"
  },
  {
    id: 16,
    title: "Sanju Portfolio Pro Hub",
    year: 2025,
    category: "Portfolio",
    tagline: "Advanced React-powered portfolio with glassmorphism & dynamic transitions.",
    desc: "React portfolio hub engineered with ambient background effects, glassmorphic cards, and project showcase filters.",
    tech: ["TypeScript", "React", "Tailwind CSS"],
    live: "https://sanju-portfolio-pro-hub.base44.app",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-laptop-code"
  },
  {
    id: 17,
    title: "Spy Detect Pro",
    year: 2025,
    category: "Cybersecurity",
    tagline: "Cybersecurity threat detection utility for analyzing security risks.",
    desc: "Interactive cybersecurity tool providing security risk assessments, password strength audits, and threat detection simulation.",
    tech: ["TypeScript", "React", "Tailwind CSS"],
    live: "https://spy-detect-pro.base44.app",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: true,
    icon: "fa-shield-halved"
  },
  {
    id: 18,
    title: "Surya Chatbot",
    year: 2025,
    category: "AI",
    tagline: "Interactive conversational AI bot with custom response logic.",
    desc: "Rule-based and generative AI chatbot designed to answer queries with an intuitive floating chat window interface.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-comments"
  },
  {
    id: 19,
    title: "Temperature Converter",
    year: 2025,
    category: "Utility",
    tagline: "Instant Celsius to Fahrenheit temperature conversion utility.",
    desc: "Sleek conversion calculator handling bi-directional transformations between Celsius, Fahrenheit, and Kelvin scales.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-temperature-high"
  },
  {
    id: 20,
    title: "Tic-Tac-Toe (Python)",
    year: 2025,
    category: "Game",
    tagline: "Classic terminal-based two-player Tic-Tac-Toe game in Python.",
    desc: "Console application written in Python demonstrating core programming logic, array manipulation, and game state management.",
    tech: ["Python"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-brands fa-python"
  },
  {
    id: 21,
    title: "Vault Secure Auth",
    year: 2025,
    category: "Authentication",
    tagline: "Secure authentication portal with login and signup UI validation.",
    desc: "Modern security portal UI implementing client-side validation, password visibility toggles, and multi-step authentication layouts.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-lock"
  },
  {
    id: 22,
    title: "VPN Landing Page",
    year: 2025,
    category: "Landing Page",
    tagline: "High-converting cybersecurity VPN subscription product landing page.",
    desc: "Commercial product landing page presenting VPN feature matrices, pricing tiers, speed test benchmarks, and user reviews.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-key"
  },
  {
    id: 23,
    title: "Web Calculator",
    year: 2025,
    category: "Utility",
    tagline: "Feature-rich web calculator with percentage and root functions.",
    desc: "Scientific-lite calculator UI offering memory recall, percentage formulas, square root functions, and keypress shortcuts.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "",
    github: "https://github.com/sanjayGL2006",
    status: "Completed",
    featured: false,
    icon: "fa-square-root-variable"
  }
];

if (typeof window !== 'undefined') {
  window.PROJECTS_DATA = PROJECTS_DATA;
}
