apiVersion: v1
kind: Secret
metadata:
  name: sanjay-portfolio-secret
  namespace: portfolio
  labels:
    app.kubernetes.io/name: sanjay-portfolio
type: Opaque
stringData:
  GEMINI_API_KEY: "your-gemini-api-key-here"
  SUPABASE_KEY: "sb_publishable_vuV_ZmS859v1QUhQHISoqg_nkN-DWFl"
  SUPABASE_SECRET_KEY: "your-supabase-secret-key-here"
