apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sanjay-portfolio.fullname" . }}-secret
  labels:
    {{- include "sanjay-portfolio.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | quote }}
  SUPABASE_KEY: {{ .Values.secrets.SUPABASE_KEY | quote }}
  SUPABASE_SECRET_KEY: {{ .Values.secrets.SUPABASE_SECRET_KEY | quote }}
